version: 0.2
phases:
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - REACT_APP_API='http://localhost:8082'
      - REACT_APP_TOKEN='123'
      - set -euo pipefail
      - ENV_JSON="$(jq --compact-output --null-input 'env | with_entries(select(.key | startswith("REACT_APP_")))')"
      - ENV_JSON_ESCAPED="$(printf "%s" "${ENV_JSON}" | sed -e 's/[\&/]/\\&/g')"
      - sed -i "s/<noscript id=\"env-insertion-point\"><\/noscript>/<script>var ENV=${ENV_JSON_ESCAPED}<\/script>/g" dist/index.html
artifacts:
  files:
    - dist/*
  discard-path: yes